# Generated by Django 5.0.4 on 2024-05-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_noticia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='contenido',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(default=None, upload_to='noticias/'),
            preserve_default=False,
        ),
    ]
