# Generated by Django 5.0.4 on 2024-05-25 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_evento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
