# Generated by Django 5.0.4 on 2024-05-26 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_noticia_options_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='pdf',
        ),
        migrations.AddField(
            model_name='pdf',
            name='evento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tasks.evento'),
        ),
    ]
